// NovaAgent — current-state system context & container view (L1/L2, M11)
// Generated by system-modeler (architecture-visualization plugin), 2026-09-18;
// refreshed for the M11 surface split, 2026-09-20.
// Source of truth: pnpm workspace manifests + scripts/dep-direction.mjs + src imports.
workspace "NovaAgent Architecture Model" {

    model {
        user = person "用户 / 开发者" {
            "在当前工作目录运行 nova：全屏 TUI（默认）、WebUI（--web）、readline 回落（--repl）、exec 非交互、qqbot 模式"
        }

        novaAgent = softwareSystem "NovaAgent (nova)" {
            "插件化跨平台本地智能体框架。内核只暴露 AgentSession 句柄 + 持久事件日志；每个 surface 是同一事件流的一家消费者"

            cli = softwareContainer "cli（产品壳）" {
                "argv → surface 装配 + config 发现 + 模型元数据；bin=nova。斜杠命令语义单源 command-runner，TUI 与 repl 两壳共用"
            }
            tuiApp = softwareContainer "tui-app（TUI surface）" {
                "nova 的默认形态：内核事件 → 纯函数层（blocks/entries/render/panels/frame）+ 按键责任链 + alternate screen 壳层"
            }
            web = softwareContainer "web（WebUI surface）" {
                "单 Node 进程 = HTTP 静态托管 + 单 WebSocket 内核事件流；自写 RFC6455、launch token → HMAC 签名 HttpOnly cookie；前端子包 ui/（React 18 + Vite + Tailwind）"
            }
            tui = softwareContainer "tui（终端原语）" {
                "零依赖：行级差分渲染、SGR 按键解码、CJK 宽度、终端能力探测"
            }
            core = softwareContainer "core（agent 内核）" {
                "provider 无关 agent 循环、append-only 消息模型、会话 JSONL v2 持久化与投影、工具调度、token 估算、请求级修剪、后台 jobs；kernel/ = AgentSession 句柄 + KernelEvent 协议 + 审批桥；compact/auto-compact/context 片段下沉至此；presentation.ts 呈现意图词汇表"
            }
            ai = softwareContainer "ai（模型客户端）" {
                "OpenAI 兼容手写客户端：fetch + SSE 流式、重试与断流自愈、usage/缓存命中提取"
            }
            plugins = softwareContainer "plugins（插件宿主）" {
                "微型插件容器 + 审批权限 + 内置工具(fs/bash/jobs/todo/search/subagent/workspace) + Skills + PTC run_code 运行时；createAgentKernel 为装配单源（host/审批桥/JobRegistry/上下文片段一处装配，provider 注入）"
            }
            qqbot = softwareContainer "qqbot（渠道插件）" {
                "第三方插件编写示范：QQ 网关 WS 状态机、token 管理、REST 发消息、nova qqbot 模式"
            }
            sessionsLog = softwareContainer "会话日志 v2（JSONL）" {
                "~/.nova/sessions/YYYY/MM/DD/，append-only 事件流 + 投影，运行目录零写入"
            }
            dataDir = softwareContainer "本地数据目录 ~/.nova/" {
                "config.json（唯一配置源）/ skills / cache/tool-outputs（工具输出溢出与 pre-compact 存档）/ models-dev.json"
            }
        }

        llmProvider = softwareSystem "OpenAI 兼容 LLM 端点" {
            "用户配置的 baseURL；SSE 流式 chat/completions + /models；prompt_cache_key 会话亲和"
        }
        modelsDev = softwareSystem "models.dev 目录" {
            "https://models.dev/api.json，24h 落盘缓存，断网回落旧缓存"
        }
        qqPlatform = softwareSystem "QQ 开放平台" {
            "api.bot.qq.com token / api.sgroup.qq.com REST / WebSocket 网关（Identify/Resume/心跳）"
        }
        browser = softwareSystem "浏览器（仅本机）" {
            "打开 nova --web 打印的带 launch token 的 localhost URL；校验后落 HttpOnly 签名 cookie"
        }

        user -> cli "运行 nova（TUI / --web / --repl / exec / qqbot）"
        user -> browser "打开打印出的 localhost URL"
        browser -> web "HTTP 静态资源 + WebSocket 帧"
        cli -> core "内核句柄、会话、工具类型、compact（11 处 import）"
        cli -> ai "构建客户端并驱动流式回复（3）"
        cli -> plugins "createAgentKernel 装配、审批、内置工具、skills、PTC（8）"
        cli -> tui "终端原语（4）"
        cli -> tuiApp "装配默认 TUI surface（1）"
        cli -> web "launchWeb（2）"
        cli -> qqbot "nova qqbot 模式（1）"
        cli -> dataDir "读 config.json、写缓存"
        tuiApp -> tui "行/宽度/能力原语（6）"
        tuiApp -> core "KernelEvent 类型与呈现词汇表（8）"
        web -> core "KernelEvent 类型与呈现词汇表（4）"
        web -> plugins "内核装配（2）"
        qqbot -> plugins "复用宿主与审批（2）"
        qqbot -> core "复用 agent 循环与会话（2）"
        plugins -> core "同一 API 的插件宿主依赖（26）"
        ai -> core "仅类型（import type，保持 provider 无关）"
        core -> sessionsLog "先写盘后入内存的 append-only 事件"
        core -> dataDir "tool-outputs 溢出落盘与压缩存档"
        ai -> llmProvider "POST {baseURL}/chat/completions（SSE）+ GET /models"
        cli -> modelsDev "后台拉取模型目录 → ~/.nova/cache/models-dev.json"
        qqbot -> qqPlatform "WS 网关 + REST 收发"
    }

    views {
        systemContext novaAgent "SystemContext" {
            include *
            autoLayout
        }
        container novaAgent "Containers" {
            include *
            autoLayout
        }
        theme default
    }
}