// NovaAgent — current-state system context & container view (L1/L2)
// Generated by system-modeler (architecture-visualization plugin), 2026-09-18.
// Source of truth: pnpm workspace manifests + scripts/dep-direction.mjs + src imports.
workspace "NovaAgent Architecture Model" {

    model {
        user = person "用户 / 开发者" {
            "在当前工作目录运行 nova CLI：TUI、readline、exec 非交互、qqbot 模式"
        }

        novaAgent = softwareSystem "NovaAgent (nova)" {
            "插件化跨平台本地智能体框架。一切皆插件 + 稳定前缀缓存 + append-only 会话日志"

            cli = softwareContainer "cli（产品壳）" {
                "全屏 TUI + readline 回落 + exec 非交互 + 配置发现 + 模型元数据；bin=nova"
            }
            tuiView = softwareContainer "tui-view（纯视图层）" {
                "零终端 IO 的呈现计算：palette/status-view/composer/popups/reasoning/frames"
            }
            tui = softwareContainer "tui（终端原语）" {
                "零依赖：行级差分渲染、SGR 按键解码、CJK 宽度、终端能力探测"
            }
            core = softwareContainer "core（agent 内核）" {
                "provider 无关 agent 循环、append-only 消息模型、会话 JSONL 持久化与投影、工具调度、token 估算、请求级修剪、后台 jobs"
            }
            ai = softwareContainer "ai（模型客户端）" {
                "OpenAI 兼容手写客户端：fetch + SSE 流式、重试与断流自愈、usage/缓存命中提取"
            }
            plugins = softwareContainer "plugins（插件宿主）" {
                "微型插件容器 + 审批权限 + 内置工具(fs/bash/jobs/todo/search/subagent/workspace) + Skills + PTC run_code 运行时"
            }
            qqbot = softwareContainer "qqbot（渠道插件）" {
                "第三方插件编写示范：QQ 网关 WS 状态机、token 管理、REST 发消息、nova qqbot 模式"
            }
            sessionsLog = softwareContainer "会话日志 v2（JSONL）" {
                "~/.nova/sessions/YYYY/MM/DD/，append-only 事件流 + 投影，运行目录零写入"
            }
            dataDir = softwareContainer "本地数据目录 ~/.nova/" {
                "config.json（唯一配置源）/ skills / cache/tool-outputs（工具输出溢出与 pre-compact 存档）/ models-dev.json"
            }
        }

        llmProvider = softwareSystem "OpenAI 兼容 LLM 端点" {
            "用户配置的 baseURL；SSE 流式 chat/completions + /models；prompt_cache_key 会话亲和"
        }
        modelsDev = softwareSystem "models.dev 目录" {
            "https://models.dev/api.json，24h 落盘缓存，断网回落旧缓存"
        }
        qqPlatform = softwareSystem "QQ 开放平台" {
            "api.bot.qq.com token / api.sgroup.qq.com REST / WebSocket 网关（Identify/Resume/心跳）"
        }

        user -> cli "运行 nova（TUI / readline / exec / qqbot）"
        cli -> core "agent 循环、会话、工具类型（29 处 import）"
        cli -> ai "构建客户端并驱动流式回复（仅 1 处直接 import，经 core 类型）"
        cli -> plugins "装配宿主、审批、内置工具、skills、PTC（11 处 import）"
        cli -> tui "终端原语（8）"
        cli -> tuiView "帧装配与呈现计算（30）"
        cli -> qqbot "nova qqbot 模式（2）"
        cli -> dataDir "读 config.json、写缓存"
        qqbot -> plugins "复用宿主与审批（2）"
        qqbot -> core "复用 agent 循环与会话（2）"
        plugins -> core "同一 API 的插件宿主依赖（20）"
        ai -> core "仅类型（import type，保持 provider 无关）"
        tuiView -> tui "行/宽度/能力原语（8）"
        tuiView -> core "共享类型（3）"
        core -> sessionsLog "先写盘后入内存的 append-only 事件"
        core -> dataDir "tool-outputs 溢出落盘与压缩存档"
        ai -> llmProvider "POST {baseURL}/chat/completions（SSE）+ GET /models"
        cli -> modelsDev "后台拉取模型目录 → ~/.nova/cache/models-dev.json"
        qqbot -> qqPlatform "WS 网关 + REST 收发"
    }

    views {
        systemContext novaAgent "SystemContext" {
            include *
            autoLayout
        }
        container novaAgent "Containers" {
            include *
            autoLayout
        }
        theme default
    }
}
