export const PLUGINS_COPY = {
  /* Generic shell for a plugin's OWN settings page (see `PluginPageSection`).
     A plugin returns its own title, intro, labels and hints — nothing here names
     one — so these four sentences are the browser's chrome around whatever a
     plugin describes. */
  'pluginPage.guideTitle': '可以这样用',
  'pluginPage.save': '保存',
  'pluginPage.saving': '保存中…',
  'pluginPage.working': '执行中…',
  'pluginPage.saved': '已保存',
  'pluginPage.failed': '这个插件没能完成该操作',
  'plugins.nav': '插件管理',
  'plugins.title': '插件管理',
  'plugins.intro': '查看运行中的插件、按需开关；开关即时生效并写入配置文件。',
  'plugins.loading': '正在读取插件清单…',
  'plugins.search': '搜索插件',
  'plugins.empty': '暂无插件。',
  'plugins.emptySearch': '无匹配插件',
  'plugins.coreGroup': '核心功能',
  'plugins.standardGroup': '基础能力',
  'plugins.advancedGroup': '扩展能力',
  'plugins.locked': '核心功能，不可关闭',
  'plugins.defaultOff': '默认关闭',
  'plugins.on': '已启用',
  'plugins.off': '已关闭',
  'plugins.switching': '切换中…',
  'plugins.switchFailed': '切换失败',
  'plugins.failedCount': '个启动失败',
  'plugins.groupToggle': '展开或收起分组',
  'plugins.lockNote': '本轮运行中（或与宿主断开）时不能切换插件开关；本轮结束后即可切换。',
  'plugins.appliedOn': '已启用「{name}」，对之后的每一次请求生效。',
  'plugins.appliedOff': '已关闭「{name}」，之后的请求不再提供它。',
  'manage.errorTitle': '操作未生效',
  'skills.nav': 'Skill 中心',
  'skills.title': 'Skill 中心',
  'skills.intro': '查看项目级与系统级的全部 Skill；关闭后不再注入后续对话。',
  'skills.loading': '正在读取 Skill 列表…',
  'skills.search': '搜索 Skill',
  'skills.empty': '暂无 Skill。在项目 .agents/skills/ 或 ~/.agents/skills/ 下放置 <名称>/SKILL.md 即可。',
  'skills.emptySearch': '无匹配 Skill',
  'skills.projectGroup': '项目级',
  'skills.userGroup': '系统级',
  'skills.projectRoot': '.agents/skills/',
  'skills.userRoot': '~/.agents/skills/',
  'skills.rootCount': '{count} 个',
  'skills.hint': 'Skill 正文按需加载：模型命中时调用 skill 工具读取全文。',
  'pluginState.pending': '等待依赖',
  'pluginState.loading': '加载中',
  'pluginState.active': '运行中',
  'pluginState.failed': '启动失败',
  'pluginState.disposed': '卸载中',
  'pluginState.disabled': '未加载',
} as const;
