/**
 * Shared types for the browser side — every shape is imported from its owner
 * (kernel protocol types live in @nova-agent/core; wire frames and the
 * transcript projection in the web package's protocol source), never
 * restated. Type-only: esbuild erases these imports, so the ui bundle ships no
 * server code.
 */
import type {
  ApprovalMode,
  ApprovalRequest,
  AskResult,
  AskUserQuestionAnswer,
  AskUserQuestionItem,
  ContextBreakdown,
  ContextCategory,
  ContextElement,
  ContextEventRecord,
  ContextPoint,
  ContextPointTiming,
  ContextTimeline,
  ContextWindowSnapshot,
  DayBucket,
  FileDiff,
  FileOpRecord,
  Goal,
  GoalStatus,
  JobSnapshot,
  KernelEvent,
  ModelGroup,
  ModelOption,
  PluginPageDescriptor,
  QuestionRequest,
  RunStats,
  SubagentProgress,
  SubagentUsage,
  TodoItem,
  ToolCallKind,
  ToolCallView,
  ToolResultView,
  TurnPhase,
  WorkspaceBucket,
} from '@nova-agent/core';
import type { ClientFrame, ConfiguredModel, GitLogEntry, GitStatusEntry, ModelCapabilities, ReadyInfo, ServerFrame, SessionListItem, WireBlock, WireDirectoryLevel, WireFileEntry, WireJobRow, WireProviderModel, WireProviderRow, WireRosterEntry, WireShell, WireSkillEntry, WireTraceRow } from '../../src/protocol';

/**
 * One row of the kernel's command catalog, derived from the frame that carries
 * it — the assembly's own shape (`Kernel.commands`), not a copy of it.
 */
export type CommandSummary = ReadyInfo['commands'][number];

export type {
  ApprovalMode,
  ApprovalRequest,
  AskResult,
  AskUserQuestionAnswer,
  AskUserQuestionItem,
  ContextBreakdown,
  ContextCategory,
  ContextElement,
  ContextEventRecord,
  ContextPoint,
  ContextPointTiming,
  ContextTimeline,
  ContextWindowSnapshot,
  DayBucket,
  Goal,
  GoalStatus,
  ClientFrame,
  ConfiguredModel,
  FileDiff,
  FileOpRecord,
  GitLogEntry,
  GitStatusEntry,
  JobSnapshot,
  KernelEvent,
  ModelCapabilities,
  ModelGroup,
  ModelOption,
  PluginPageDescriptor,
  QuestionRequest,
  ReadyInfo,
  RunStats,
  ServerFrame,
  SessionListItem,
  SubagentProgress,
  SubagentUsage,
  TodoItem,
  ToolCallKind,
  ToolCallView,
  ToolResultView,
  TurnPhase,
  WireBlock,
  WorkspaceBucket,
  WireDirectoryLevel,
  WireFileEntry,
  WireJobRow,
  WireProviderModel,
  WireProviderRow,
  WireRosterEntry,
  WireShell,
  WireSkillEntry,
  WireTraceRow,
};